---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<center> <h2> Nazir Adam Sharifi </h1> </center>
<center> <h4> 17 Normandy Grange, Garrison, NY </h2> </center>
<center> <h4> 607-342-2191 </center> • nas258@cornell.edu </h1> </center>

#### **Education**
<hr/>
<p style="text-align:left;"> **Cornell University** <span style="float:right;"> *Ithaca, NY*</span>
<p style="text-align:left;"> **M.S./Ph.D. in Soil and Crop Sciences**	<span style="float:right;">*May 2024 – Present* </span>
</p>
•	GPA: N/A

<br/>

<p style="text-align:left;"> **Cornell University** <span style="float:right;"> *Ithaca, NY* </span>
<p style="text-align:left;"> **B.S. in Environment & Sustainability**
<span style="float:right;"> *August 2020 – May 2024* </span>
</p>
•	Minor: Sustainable Agricultural and Food Systems  
•	Distinction in Research: Plant Sciences  
•	GPA: 4.006  
<hr/>

#### **Publications**
<hr/>
Sharifi, N. A., Loria, K., Pelzer, C. J., Silva, E. M., Darby, H. M., Pethybridge, S., Mallory, E. B., Matthew, R. R., (2024). High Seeding Rates Suppress Weeds and Increase Yield in Organic No-Till Planted Black Bean. Agronomy Journal. (in preparation)
<hr/>
#### **Conference Presentations**
<hr/>
Sharifi, N. A., Pelzer, C. J., Menalled, U. D., Loria, K., Wayman, S., Silva, E. M., Matthew, R. R., (2024, October). Optimizing Weed Management and Crop Yield in Organic No-till Planted Corn Production. Oral presentation at the 2024 ASA, CSSA, SSSA International Annual Meeting in Organic Management Systems Oral Session (includes graduate student competition), San Antonio, TX (abstract accepted)

Sharifi, N. A., Loria, K., Pelzer, C. J., Silva, E. M., Darby, H. M., Pethybridge, S., Mallory, E. B., Matthew, R. R., (2024, October). Enhanced Weed Suppression and Profitability with High Seeding Rates in Organic No-till Planted Black Bean. Poster presentation at the 2024 ASA, CSSA, SSSA International Annual Meeting in Organic Management Systems Poster Session (includes graduate student competition), San Antonio, TX (abstract accepted)

Sharifi, N. A., Loria, K., Pelzer, C. J., Silva, E. M., Darby, H. M., Pethybridge, S., Mallory, E. B., Matthew, R. R., (2023, October). Higher Seeding Rates Enhance Weed Suppression, Yield and Profitability for Organic No-till Black Bean Production. Oral presentation at the 2023 ASA, CSSA, SSSA International Annual Meeting in Organic Management Systems General Oral Session (includes graduate student competition), St. Louis, MO 

Sharifi, N. A., Loria, K., Pelzer, C. J., Silva, E. M., Darby, H. M., Pethybridge, S., Mallory, E. B., Matthew, R. R., (2023, July). High Seeding Rates Optimize Weed Suppression and Profitability in Organic No-till Planted Black Bean. Oral presentation at the 2023 University at Buffalo Undergraduate Research Conference (virtual) 

Sharifi, N. A., Loria, K., Pelzer, C. J., Silva, E. M., Darby, H. M., Pethybridge, S., Matthew, R. R., (2023, April). Increasing Planting Rates to Optimize No-till Black Bean Production for Organic Farmers. Oral presentation at the 2023 International Association of Students in Agricultural and Related Sciences (IAAS) USA Summit & National Research Symposium, Ithaca, NY 

Sharifi, N. A., Loria, K., Pelzer, C. J., Silva, E. M., Darby, H. M., Pethybridge, S., Matthew, R. R., (2023, March). Effect of Seeding Rate on Organic No-till Black Bean Production. Oral presentation at the 24th Annual University of Maryland National Conference, College Park, MD

Sharifi, N. A., Loria, K., Pelzer, C. J., Silva, E. M., Darby, H. M., Pethybridge, S., Matthew, R. R., (2022, November). Effect of Seeding Rate on Organic No-till Black Bean Production. Oral presentation at the 2022 ASA, CSSA, SSSA International Annual Meeting in Organic Management Systems General Oral (includes graduate student competition), Baltimore, MD

Sharifi, N. A., Loria, K., Pelzer, C. J., Silva, E. M., Darby, H. M., Pethybridge, S., Matthew, R. R., (2022, July). Effect of Seeding Rate on Organic No-till Black Bean Production. Poster presentation at the 2022 University at Buffalo Undergraduate Research Conference (virtual) 

Sharifi, N. A., Loria, K., Pelzer, C. J., Silva, E. M., Darby, H. M., Pethybridge, S., Matthew, R. R., (2022, March). Introduction to the Black Bean Seeding Rate Experiment. Poster presentation at the 23rd Annual University of Maryland National Conference, College Park, MD
<hr/>

#### **Research Experience**
<hr/>
<p style="text-align:left;"> **Sustainable Cropping Systems Lab** <span style="float:right;"> *2021 – 2024* </span> </p>

*Research Assistant III*  
•	Lead a 2-year, multi-site experiment across East and Central US on the effects of seeding rate in organic no-till black bean production  
•	Conduct photosynthetically active radiation (PAR) sampling, plant/soil sampling, sample processing, and plot maintenance for various lab experiments  
•	Assist graduate students with research and experimental processes at 3 different lab locations in a variety of demanding outdoor/indoor lab environments  
•	Create experimental protocols, perform and structure data entry in Excel, analyze data in R, and construct presentations for conferences  


<br/>

<p style="text-align:left;"> **Nuponix Labs** <span style="float:right;"> *2021 – 2024* </span> </p>

*Aquaponics Research Internship*  
•	Conduct nutrient/pH examinations for the aquaponics systems to optimize tilapia and hemp growth   
•	Assist Chief Science Officers in cloning, growing, trimming, and harvesting hemp samples  
•	Process yield samples, perform data entry in Excel, and analyze data on hemp variety trials  
•	Support the General Manager in maintaining the 40,000 sq ft CBD/CBG/CBC facility  

<br/>

<p style="text-align:left;"> **Controlled Environment Agriculture (CEA) Lab** <span style="float:right;"> *2021 – 2022* </span> </p>

*Aquaponics Undergraduate Researcher*  
•	Set up aquaponics research projects with various plants and leafy greens  
•	Worked with conventional mineral fertilizer, recirculating aquaponics, and decoupled aquaponics systems with added nutrients  
•	Assisted with transplanting, graphing/analyzing data, summarizing results, management of plant harvest/samples  
•	Conducted research with elements of both aquaculture and hydroponics to advance the field of aquaponics  


<br/>

<p style="text-align:left;"> **Dairy Cattle Biology Lab & Grōv Technologies** <span style="float:right;"> *2022* </span> </p>

*Hydroponics Research Operator*  
•	Assisted in a study testing the effect of hydroponically grown feed on milk production efficiency, nutrient utilization, and potential environmental impact reduction for dairy cattle  
•	Operated and maintained a hydroponics unit constructed by Grōv Technologies that grew sprouted grain feed  
•	Sampled, harvested, and transported the hydroponic-grown feed for dairy cattle consumption  
•	Worked collaboratively with graduate students and research assistants to execute experimental protocols  
<hr/>
#### **Teaching**
<hr/>
<p style="text-align:left;"> **The Global Food, Energy, and Water Nexus – Engaging the US, China, and India for a Sustainable Future | ANSC/FDSC/AEM/CHEME 4880, ANSC/FDSC/AEM 6880, CHEME 6780/CEE5820** <span style="float:right;"> *2023* </span> </p>

*Teaching Assistant*  
•	Support teaching staff for a course in collaboration with four departments at Cornell, two universities in China, and one in India
•	Lead instructional sessions and moderate debates for undergraduate and graduate students under the general guidance of teaching staff  
•	Grade exams/assignments and provide detailed feedback to ensure students learn course concepts
•	Teach and work closely with China Agricultural University Dual-Degree students from the course

<br/>